dataloader:
    generator_type: PolynomialGenerator
    generator:
        num_nodes: 2
        num_edges: 2
        max_terms: 4
        num_realizations: 100
        allowed_operations: ["+", "-", "*", "/", "cos", "log", "sin", "exp"]
        real_numbers_realizations: False
        keep_graph: False
        keep_data: False
        real_numbers_variables: False
        num_variables: 2
        max_powers: 1
        seed: 1
    train_samples: 1000
    valid_samples: 500
    batch_size: 64
    num_workers: 8
    data_dir: "./data"
