dataloader:
    generator_type: PolynomialGenerator
    generator:
        num_variables: 2
        max_terms: 4
        num_realizations: 200
        allowed_operations: ["+", "-", "*", "/", "cos", "log", "sin", "exp"]
        real_const_decimal_places: 3
        real_constants_min: -10
        real_constants_max: 10
        max_const_exponent: 3
        sample_interval: [-10, 10]
        use_math_constants: True
        keep_graph: False
        keep_data: False
        max_powers: 3
        seed: 1
    train_samples: 100
    valid_samples: 50
    batch_size: 64
    num_workers: 8
    data_dir: "./data"
