dataloader:
    generator_type: PolynomialGenerator
    generator:
        num_variables: 4
        max_terms: 4
        num_realizations: 200
        allowed_operations: ["+", "-", "*", "/", "cos", "log", "sin", "exp"]
        real_numbers_realizations: False
        keep_graph: False
        keep_data: False
        real_numbers_variables: False
        max_powers: 3
        seed: 1
    train_samples: 100
    valid_samples: 100
    batch_size: 64
    num_workers: 8
    data_dir: "./data"
